### PR TITLE
Fix compatibility of Login Handler with IPS 4.3

### LINKED ISSUE #110: core_login_handlers does not exist in 4.3
On a fresh install it appears it was changed to `core_login_methods` with a slightly different structure.

### PR DESCRIPTION
**Pull request by aStonePenguin**
Fixes #110 #108 #107 #106 and #87 

API key/method settings will probably need to be readded unless the 4.3 update merged those or someone else wants to add a merge script too.

### CODE REVIEW

**Comment by seboxxl** [comment]
Could you make #87 changes compatible with IPB 4.2?

**Comment by madman32395** [comment]
More than likely it would be updated to 4.3, be silly to continue support for outdated systems.

**Comment by seboxxl** [comment]
I'm just using IPB 4.2 for now, I don't have time to update style and everything to 4.3, but it would be nice to fix random "Something went wrong" error.

**Comment by aStonedPenguin** [comment]
just manually take the changes from the second commit @seboxxl

**Comment by madman32395** [comment]
4.3 didn't make any breaking style changes, majority was code wise.

**Comment by seboxxl** [comment]
Looks like uploading just new Steam.php works fine for me. Thanks!

**Comment by CamerDisco** [comment]
Still I don't have steam profile settings page, even with this fix.

**Comment by madman32395** [comment]
I've said in a pm what's still broke and that it wasn't a 4.3 fix. It's a
bandage I'll give ya that.

File: upload/system/Login/Steam.php [hunk 1]
```diff
@@ -238,60 +248,52 @@ public function canChange($type, \IPS\Member $member)
...
+	/**
+	 * Gets a url param and sanitizes it for openid
+	 *
+	 * @param    string    $param  url param
+	 *
+	 * @return    string
+	 */
+	private function get($param)
+	{
+		return str_replace(' ', '+', trim(urldecode(\IPS\Request::i()->{$param})));
```
Comment (Lavoaster) [inline upload/system/Login/Steam.php]: In my experience, it's best to the parameter without it having gone through IPS parameter sanitization. Tricks like replacing spaces with +'s aren't always reliable as I've seen them fail in the past.

File: upload/system/Login/Steam.php [hunk 2]
```diff
@@ -238,60 +248,52 @@ public function canChange($type, \IPS\Member $member)
...
 	protected function validate()
 	{
 		$params = array(
-			'openid.signed' => \IPS\Request::i()->openid_signed,
-			'openid.sig' => str_replace(' ', '+', \IPS\Request::i()->openid_sig),
-			'openid.ns' => 'http://specs.openid.net/auth/2.0',
+			'openid.assoc_handle' => $this->get('openid_assoc_handle'),
+			'openid.signed' => $this->get('openid_signed'),
+			'openid.sig' => $this->get('openid_sig'),
+			'openid.mode' => 'check_authentication'
```
Comment (Lavoaster) [inline upload/system/Login/Steam.php]: I'm assuming that this isn't functional change, just code cleanup?

File: upload/system/Login/Steam.php [hunk 3]
```diff
@@ -238,60 +248,52 @@ public function canChange($type, \IPS\Member $member)
...
-
-			$key = $data[0];
-			unset($data[0]);
-
-			$values[$key] = implode(':', $data);
-		}
-
 		// Return our final value
-		return $values['is_valid'] === 'true' ? $steamID64 : false;
+		return (preg_match('/is_valid\s*:\s*true/i', $response) && ($steamID64 != 0)) ? $steamID64 : false;
```
Comment (Lavoaster) [inline upload/system/Login/Steam.php]: I'm not a fan of regex based solutions. The previous solution properly parsed the return contents, unless something has changed that I'm unaware of.

**Review by LavaToaster — COMMENTED** [review]
Thanks for doing this @aStonedPenguin. I've left you a few comments, but I'll look to pull this in very soon, once IPS sorts out my renewal.

File: upload/system/Login/Steam.php (hunk 1 above)
Comment (aStonedPenguin) [reply upload/system/Login/Steam.php]: Unless there's a way to tell when ipb force urlencodes it that's the best I can think of.

File: upload/system/Login/Steam.php (hunk 2 above)
Comment (aStonedPenguin) [reply upload/system/Login/Steam.php]: Just cleanup.

File: upload/system/Login/Steam.php (hunk 3 above)
Comment (aStonedPenguin) [reply upload/system/Login/Steam.php]: It's cleaner in my opinion, it's also how LightOpenID does it.

File: upload/system/Login/Steam.php (hunk 1 above)
Comment (Lavoaster) [reply upload/system/Login/Steam.php]: Just use `$_GET`, as the previous code did, because IPS doesn't modify the global variable. ;) It's safe to use it directly.

File: upload/system/Login/Steam.php (hunk 2 above)
Comment (Lavoaster) [reply upload/system/Login/Steam.php]: 👍

File: upload/system/Login/Steam.php (hunk 3 above)
Comment (Lavoaster) [reply upload/system/Login/Steam.php]: Ehhhhhhhhhhhh, I don't particularly agree. It's less code, but it doesn't mean it's cleaner. But to be honest, we only care about `is_valid` so 🤷‍♂️, sure.

File: upload/system/Login/Steam.php (hunk 1 above)
Comment (Lavoaster) [reply upload/system/Login/Steam.php]: Alright, this is the only thing I'm against pulling in. If you change this to 

```php
        $value = isset($_GET[$param]) ? $_GET[$param] : null;

        if ($value === null) {
			return null;
        }

		return trim(urldecode($value));
```

Then 👍

If only IPS's min requirement was PHP 7.0 and not 5.6 then it could be

```php
        if ($value = $_GET[$param] ?? false) {
			return null;
        }

		return trim(urldecode($value));
```

Comment (madman32395) [reply upload/system/Login/Steam.php]: well... php 7.0+ is their recommended. 5.6 and 7.0 are EOL, 7.1 is almost there, 7.2 being current. why not start supporting at least 7.0 only.  if someones host still has them on 5.6 or lower, they need to re-evaluate their webhosting.

Comment (Lavoaster) [reply upload/system/Login/Steam.php]: It's not worth the aggravation when it's easy enough to support. 

FYI PHP 5.6 &  7.0 become unsupported versions this year [source](https://secure.php.net/supported-versions.php), which really leaves 7.1 / 7.2 as "Officially support by PHP Maintainer". 

Some additional FYI's is that PHP 5.6, 7.0 (and possibly older ones) are still going to be around for a while as vendors such as Canonical and Red Hat will maintain support for LTS distributions that contain PHP binaries in their official repos that they offer LTS support on.

**Review by LavaToaster — APPROVED** [review]

**Comment by Lavoaster** [comment]
Hey @aStonedPenguin,

Just thought I'd give you a heads up that I ended up rewriting all of the plugins code so that it's an application, and integrates with the new 4.3 style Login Methods.

**Comment by island55** [comment]
is the new version of Steam Login compatible with 4.2 versions? Or should I remain using the current version I've already got installed?

**Comment by Lavoaster** [comment]
No, it is not compatible with 4.2.

**Comment by island55** [comment]
Thank you for prompt response and I appreciate your time in continuing to support this. When the time comes to upgrade to 4.3 then we'll upgrade! G'day sir
